package com.aquiva.autotests.rc.page.opportunity.ngbsquotingwizard.modal;

import com.aquiva.autotests.rc.page.opportunity.ngbsquotingwizard.NGBSQuotingWizardPage;
import com.codeborne.selenide.ElementsCollection;
import com.codeborne.selenide.SelenideElement;

import static com.codeborne.selenide.Selectors.byText;
import static com.codeborne.selenide.Selenide.*;
import static com.codeborne.selenide.SetValueOptions.withDate;
import static java.time.LocalDate.now;

/**
 * This is a modal window in {@link NGBSQuotingWizardPage} (Quote Details tab)
 * with form for populating and configuring Playbooks activated by clicking on "Generate and Preview" button.
 * <p>
 * Some or all of Playbooks could be selected from the list.
 * Then, Playbooks could be generated by clicking on "Generate and Preview" button.
 * </p>
 */
public class ConfigurePlaybooksModal {

    //  Number constants used in the form
    public static final String PAYMENT_TERMS_DAYS = "30";
    public static final String TRIAL_PERIOD_DAYS = "30";

    public final ElementsCollection addPlaybookButtons = $$("[for*='add-checkbox']");
    public final SelenideElement generateAndPreviewButton = $(byText("Generate and Preview"));
    public final SelenideElement effectiveDateInputField = $("#effective-date");
    public final SelenideElement attachAllToOpportunityButton = $(byText("Attach all to Opportunity"));
    public final ElementsCollection successAttachedIcons = $$("[iconname='success']");
    private final SelenideElement paymentTermsPicklist = $x("//div[label[text()=' Incremental Dates ']]//select");

    /**
     * Select and populate all Playbooks in modal window.
     */
    public void populateAllPlaybooks() {
        addPlaybookButtons.asDynamicIterable().forEach(button -> button.click());
        effectiveDateInputField.setValue(withDate(now()));
        paymentTermsPicklist.selectOptionContainingText(PAYMENT_TERMS_DAYS);
    }
}
