package com.aquiva.autotests.rc.page.opportunity.ngbsquotingwizard.modal;

import com.aquiva.autotests.rc.page.opportunity.ngbsquotingwizard.NGBSQuotingWizardPage;
import com.codeborne.selenide.ElementsCollection;
import com.codeborne.selenide.SelenideElement;

import static com.codeborne.selenide.Condition.attribute;
import static com.codeborne.selenide.Selectors.byText;
import static com.codeborne.selenide.Selenide.$;

/**
 * Modal window in {@link NGBSQuotingWizardPage} (Quote Details tab)
 * activated by clicking on "Generate PDF" button.
 * <p>
 * Some or all PDF templates could be selected from the list.
 * Then, PDF Templates could be generated by clicking on "Generate and Preview" button.
 * </p>
 */
public class PdfGenerateModal {
    private final SelenideElement dialogContainer = $("pdf-select-template");

    public final ElementsCollection templateCheckboxes = dialogContainer.$$(".slds-checkbox.ng-star-inserted");
    public final ElementsCollection msaRadioButtons = dialogContainer.$$("[for^='template-radio']");
    public final ElementsCollection pdfOptionsCheckboxes = dialogContainer.$$("input[name='templates']");
    public final ElementsCollection preselectedPdfTemplatesCheckboxes =
            dialogContainer.$$(".slds-checkbox > input:disabled");
    public final ElementsCollection preselectedPdfTemplatesNames =
            dialogContainer.$$(".slds-checkbox > input:disabled + label");
    public final ElementsCollection notSelectedPdfTemplatesCheckboxes =
            dialogContainer.$$(".slds-checkbox > input:enabled");
    public final ElementsCollection notSelectedPdfTemplatesNames =
            dialogContainer.$$(".slds-checkbox > input:enabled + label");
    public final ElementsCollection pdfAllTemplateNames =
            dialogContainer.$$("span.slds-form-element__label");
    public final SelenideElement infoMessage = dialogContainer.$("p");

    //  Buttons (footer)
    public final SelenideElement generateAndPreviewPdfButton = dialogContainer.$(byText("Generate and Preview"));
    public final SelenideElement cancelButton = dialogContainer.$(byText("Cancel"));

    /**
     * Select all available PDF templates and mark them checked.
     */
    public void selectAllPdfTemplates() {
        for (var button : pdfOptionsCheckboxes.exclude(attribute("disabled"))) {
            button.sibling(0).click();
        }
    }
}
